// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLCRUD.Data;

#nullable disable

namespace SQLCRUD.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250928174628_RemovePriceFieldComplete")]
    partial class RemovePriceFieldComplete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SQLCRUD.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            DateCreated = new DateTime(2025, 8, 29, 23, 16, 27, 777, DateTimeKind.Local).AddTicks(8419),
                            Description = "High-performance laptop with latest processor",
                            IsActive = true,
                            Name = "Laptop Pro 15",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            DateCreated = new DateTime(2025, 9, 13, 23, 16, 27, 777, DateTimeKind.Local).AddTicks(9340),
                            Description = "Ergonomic wireless mouse with long battery life",
                            IsActive = true,
                            Name = "Wireless Mouse",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 3,
                            Category = "Furniture",
                            DateCreated = new DateTime(2025, 9, 21, 23, 16, 27, 777, DateTimeKind.Local).AddTicks(9348),
                            Description = "Comfortable ergonomic office chair",
                            IsActive = true,
                            Name = "Office Chair",
                            StockQuantity = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
