// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLCRUD.Data;

#nullable disable

namespace SQLCRUD.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SQLCRUD.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            DateCreated = new DateTime(2025, 8, 28, 22, 0, 48, 96, DateTimeKind.Local).AddTicks(9516),
                            Description = "High-performance laptop with latest processor",
                            IsActive = true,
                            Name = "Laptop Pro 15",
                            Price = 1299.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            DateCreated = new DateTime(2025, 9, 12, 22, 0, 48, 97, DateTimeKind.Local).AddTicks(114),
                            Description = "Ergonomic wireless mouse with long battery life",
                            IsActive = true,
                            Name = "Wireless Mouse",
                            Price = 49.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 3,
                            Category = "Furniture",
                            DateCreated = new DateTime(2025, 9, 20, 22, 0, 48, 97, DateTimeKind.Local).AddTicks(119),
                            Description = "Comfortable ergonomic office chair",
                            IsActive = true,
                            Name = "Office Chair",
                            Price = 299.99m,
                            StockQuantity = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
